# Generated by Django 4.0.2 on 2022-04-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo_specs',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='species',
            field=models.CharField(default='none', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
