# Generated by Django 4.0.2 on 2022-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_image_rename_content_post_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo_specs',
            new_name='photo_Specs',
        ),
        migrations.AddField(
            model_name='post',
            name='county',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
