# Generated by Django 4.0.2 on 2022-04-08 16:41

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_photo_specs_post_photo_specs_post_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='date_Taken',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='species',
            field=models.CharField(max_length=200),
        ),
    ]
