# Generated by Django 4.0.2 on 2022-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_Taken',
        ),
    ]
