# Generated by Django 4.0.2 on 2022-04-08 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_Taken',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
