# Generated by Django 4.0.2 on 2022-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_date_taken_post_date_captured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_Specs',
        ),
        migrations.AddField(
            model_name='post',
            name='aperture',
            field=models.CharField(default='f/4.0', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='camera',
            field=models.CharField(default='ILCE-1', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='ev',
            field=models.CharField(default='0.0', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='iso',
            field=models.CharField(default='400', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='lens',
            field=models.CharField(default='FE 600mm F4 GM', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='mm',
            field=models.CharField(default='600', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='shutter',
            field=models.CharField(default='1/3200', max_length=200),
        ),
    ]
