# Generated by Django 4.0.2 on 2022-04-08 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_date_captured_post_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sequence',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_Date',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
    ]
