# Generated by Django 4.0.2 on 2022-04-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_sequence_post_slug_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sequence',
        ),
    ]
