# Generated by Django 4.0.2 on 2022-04-08 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_Date',
            field=models.CharField(default=datetime.date.today, max_length=200),
        ),
    ]
