# Generated by Django 4.0.2 on 2022-04-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_slug_date_post_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sequence',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
