# Generated by Django 4.0.2 on 2022-04-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_captured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(max_length=260),
        ),
    ]
