# Generated by Django 4.0.2 on 2022-02-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0002_bird_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='bird',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='bird',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
