# Generated by Django 4.0.2 on 2022-02-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0003_rename_bird_bird_name_alter_bird_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesCode', models.CharField(max_length=100, unique=True)),
                ('comName', models.CharField(max_length=100, unique=True)),
                ('locId', models.CharField(max_length=100, unique=True)),
                ('locName', models.CharField(max_length=100, unique=True)),
                ('obsDt', models.CharField(max_length=100, unique=True)),
                ('howMany', models.CharField(max_length=100, unique=True)),
                ('lat', models.CharField(max_length=100, unique=True)),
                ('lng', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
