# Generated by Django 4.0.2 on 2022-02-24 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0006_alter_observation_comname_alter_observation_howmany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='mod_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
