# Generated by Django 4.0.2 on 2022-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0007_observation_mod_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('speciesCode', 'obsDt', 'locId'), name='no_duplicate_obs'),
        ),
    ]
