# Generated by Django 4.0.2 on 2022-02-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0008_observation_no_duplicate_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='type',
            field=models.CharField(default='Rapter', max_length=100),
            preserve_default=False,
        ),
    ]
