# Generated by Django 4.0.2 on 2022-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0010_notable_notable_no_duplicate__notable_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='type',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='comName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='howMany',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='lat',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='lng',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='locId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='locName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='obsDt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notable',
            name='speciesCode',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='comName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='howMany',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lat',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lng',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='locId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='locName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obsDt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='observation',
            name='speciesCode',
            field=models.CharField(max_length=1000),
        ),
    ]
