# Generated by Django 4.0.2 on 2022-09-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandion', '0011_alter_bird_id_alter_bird_name_alter_bird_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='state',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
