# Generated by Django 4.0.2 on 2022-09-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0002_rename_ew_bird_ewbird'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ewBird',
            new_name='Eagles',
        ),
    ]
