# Generated by Django 4.0.2 on 2022-09-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0003_rename_ewbird_eagles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eagles',
            new_name='Eagle',
        ),
    ]
