# Generated by Django 4.0.2 on 2022-09-30 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0005_states'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
