# Generated by Django 4.0.2 on 2022-10-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0006_rename_states_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLocations',
            fields=[
                ('locId', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('locName', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('howMany', models.IntegerField()),
            ],
        ),
    ]
