# Generated by Django 4.0.2 on 2022-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0007_toplocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toplocations',
            name='locId',
        ),
        migrations.RemoveField(
            model_name='toplocations',
            name='state',
        ),
        migrations.AlterField(
            model_name='toplocations',
            name='locName',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
