# Generated by Django 4.0.2 on 2022-10-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0008_remove_toplocations_locid_remove_toplocations_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStates',
            fields=[
                ('state', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('howMany', models.IntegerField()),
            ],
        ),
    ]
