# Generated by Django 4.0.2 on 2022-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0009_topstates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStateLocationTwo',
            fields=[
                ('state', models.CharField(max_length=1000)),
                ('locName', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('howMany', models.IntegerField()),
            ],
        ),
    ]
