# Generated by Django 4.0.2 on 2022-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0010_topstatelocationtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EagleScore',
            fields=[
                ('state', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('eaglescore', models.IntegerField()),
            ],
        ),
    ]
