# Generated by Django 4.0.2 on 2022-10-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0011_eaglescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
