# Generated by Django 4.0.2 on 2022-10-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirdCounter', '0012_flags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flags',
            new_name='Flag',
        ),
    ]
